const Constants ={
    ADD_FRIEND:"ADD_FRIEND",
    REMOVE_FRIEND:"REMOVE_FRIEND",
    POST_COMMENT:"POST_COMMENT",
    REMOVE_COMMENT:"REMOVE_COMMENT",
    LIKE_MOVIE:"LIKE_MOVIE",
    UNLIKE_MOVIE:"UNLIKE_MOVIE",
    FETCH_FAVORITE_MOVIES:"FETCH_FAVORITE_MOVIES",
    CANCEL_FETCHING:"CANCEL_FETCHING",
    ADD_ERROR:"ADD_ERROR",
    CLEAR_ERROR:"CLEAR_ERROR",
    POST_REVIEW:"POST_REVIEW",
    REMOVE_REVIEW:"REMOVE_REVIEW",
    ADD_SEARCH_QUERY:"ADD_SEARCH_QUERY",
    GET_SEARCH_QUERY:"GET_SEARCH_QUERY",
    SEARCH_MOVIE:"SEARCH_MOVIE",
    GET_UPCOMING_MOVIES_SUCCESS:"GET_UPCOMING_MOVIES_SUCCESS",
    GET_NOW_PLAYING_SUCCESS:"GET_NOW_PLAYING_SUCCESS"

}

export default Constants;